### ISSUE TITLE
Dual licensing

### ISSUE THREAD

**Issue by notetiene** [nakkaya/static#28]
I was wondering if it would be possible to add an other license than EPL.  Sadly, some words in EPL makes it incompatible with the GPL (and other licenses).

Would it be possible to license it under a license like LGPL, MIT or the Simplified BSD Licence?

(By the way, thanks for that awesome software)

**Comment by nakkaya** [comment]
Sure, How about BSD 2-Clause License? (If thats what you mean by Simplified BSD)

**Comment by notetiene** [comment]
Yes, that's what I was referring ;)

**Comment by nakkaya** [comment]
I've updated the license section.

Best,
